### PR TITLE
CI setup with e2e tests

### PR DESCRIPTION
**Pull request by prometheansacrifice**

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
Timeout on CI. I think I'm not setting the timeout right

**Comment by prometheansacrifice** [comment]
https://dev.azure.com/prometheansacrifice/vscode-merlin-fork/_build/results?buildId=1183

**Comment by prometheansacrifice** [comment]
https://dev.azure.com/prometheansacrifice/vscode-merlin-fork/_build/results?buildId=1188

**Comment by andreypopp** [comment]
Thanks!

**Pull request merged**
